[#-- jQuery--]
[@js src="lib/jquery/jquery-1.11.3.min.js" /]
[#-- zui --]
[@js src="lib/zui/js/zui.min.js" /]
[@js src="js/modernizr.custom.js" /]
[#--[@js src="lib/bootstrap/js/bootstrap.min.js" /]--]
[@js src="js/jquery.easing.1.3.js" /]
[@js src="js/css3-animate-it.js" /]
[@js src="js/jquery.appear.js" /]
[@js src="js/stellar.js" /]
[@js src="js/classie.js" /]
[@js src="js/uisearch.js" /]
[@js src="js/jquery.cubeportfolio.min.js" /]
[@js src="lib/google-code-prettify/prettify.js" /]
[@js src="js/animate.js" /]
[@js src="js/custom.js" /]
[#-- jQuery Cookie --]
[@js src="lib/jquery/cookie/jquery.cookie.min.js" /]
[#-- layer --]
[@js src="lib/layer/layer.js" /]
[#-- js template --]
[@js src="lib/laytpl/laytpl.js" /]
[#-- pagination --]
[@js src="lib/laypage/laypage.js" /]

[#-- 公共 --]
[@js src="js/common.js" /]
[@js src="js/footer.js"/]